FROM node:18 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

# Copiar os arquivos de build
COPY --from=build /app/dist/fila-flex/browser /usr/share/nginx/html

# Copiar configuração nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar script de entrada
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

# Definir variáveis de ambiente padrão
ENV API_URL=http://localhost:8080
ENV PRODUCTION=true
ENV APP_VERSION=1.0.0

EXPOSE 80

# Usar ENTRYPOINT para executar nosso script
ENTRYPOINT ["/docker-entrypoint.sh"]